
CREATE DATABASE BAITHI;
GO
USE BAITHI;
GO

-- Tạo bảng NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MANCC CHAR(5) PRIMARY KEY,
    TENNCC NVARCHAR(100),
    QUOCGIA NVARCHAR(50),
    LOAINCC NVARCHAR(50)
);

-- Tạo bảng DUOCPHAM
CREATE TABLE DUOCPHAM (
    MADP CHAR(5) PRIMARY KEY,
    TENDP NVARCHAR(100),
    LOAIDP NVARCHAR(50),
    GIA DECIMAL(10, 2)
);

-- Tạo bảng PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    SOPN CHAR(5) PRIMARY KEY,
    NGNHAP DATE,
    MANCC CHAR(5),
    LOAINHAP NVARCHAR(50),
    FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
);

-- Tạo bảng CTPN
CREATE TABLE CTPN (
    SOPN CHAR(5),
    MADP CHAR(5),
    SOLUONG INT,
    PRIMARY KEY (SOPN, MADP),
    FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN),
    FOREIGN KEY (MADP) REFERENCES DUOCPHAM(MADP)
);
GO
-- Nhập dữ liệu vào bảng NHACUNGCAP
INSERT INTO NHACUNGCAP VALUES
('NCC01', N'Phuc Hung', N'Viet Nam', N'Thuong xuyen'),
('NCC02', N'J. B. Pharmaceuticals', N'India', N'Vang lai'),
('NCC03', N'Sapharco', N'Singapore', N'Vang lai');

-- Nhập dữ liệu vào bảng DUOCPHAM
INSERT INTO DUOCPHAM VALUES
('DP01', N'Thuoc ho PH', N'Siro', 120000),
('DP02', N'Zecuf Herbal CouchRemedy', N'Vien nen', 200000),
('DP03', N'Cotrim', N'Vien sui', 80000);

-- Nhập dữ liệu vào bảng PHIEUNHAP
INSERT INTO PHIEUNHAP VALUES
('00001', '2017-11-22', 'NCC01', N'Noi dia'),
('00002', '2017-12-04', 'NCC03', N'Nhap khau'),
('00003', '2017-12-10', 'NCC02', N'Nhap khau');

-- Nhập dữ liệu vào bảng CTPN
INSERT INTO CTPN VALUES
('00001', 'DP01', 100),
('00001', 'DP02', 200),
('00003', 'DP03', 543);
GO

--câu 3
ALTER TABLE DUOCPHAM
ADD CONSTRAINT CK_LOAIDP_GIA CHECK (
    NOT (LOAIDP = N'Siro' AND GIA <= 100000)
);
GO

--câu 4
CREATE TRIGGER TRG_CHECK_QUOCGIA_LOAINHAP
ON PHIEUNHAP
AFTER INSERT, UPDATE
AS
BEGIN
    IF EXISTS (
        SELECT 1
        FROM INSERTED I
        JOIN NHACUNGCAP N ON I.MANCC = N.MANCC
        WHERE N.QUOCGIA <> N'Viet Nam' AND I.LOAINHAP <> N'Nhap khau'
    )
    BEGIN
        RAISERROR ('Phiếu nhập của nhà cung cấp nước ngoài phải có loại nhập là "Nhập khẩu".', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

--câu 5
SELECT * 
FROM PHIEUNHAP
WHERE MONTH(NGNHAP) = 12 AND YEAR(NGNHAP) = 2017
ORDER BY NGNHAP ASC;


--câu 6
SELECT TOP 1 CTPN.MADP, SUM(CTPN.SOLUONG) AS TotalQuantity
FROM CTPN
JOIN PHIEUNHAP ON CTPN.SOPN = PHIEUNHAP.SOPN
WHERE YEAR(PHIEUNHAP.NGNHAP) = 2017
GROUP BY CTPN.MADP
ORDER BY TotalQuantity DESC;


--câu 7
SELECT DISTINCT DUOCPHAM.*
FROM DUOCPHAM
WHERE DUOCPHAM.MADP NOT IN (
    SELECT DISTINCT CTPN.MADP
    FROM CTPN
    JOIN PHIEUNHAP ON CTPN.SOPN = PHIEUNHAP.SOPN
    JOIN NHACUNGCAP ON PHIEUNHAP.MANCC = NHACUNGCAP.MANCC
    WHERE NHACUNGCAP.LOAINCC = N'Vang lai'
);

--câu 8
SELECT NHACUNGCAP.MANCC, NHACUNGCAP.TENNCC
FROM NHACUNGCAP
WHERE NOT EXISTS (
    SELECT DUOCPHAM.MADP
    FROM DUOCPHAM
    WHERE DUOCPHAM.GIA > 100000
    AND DUOCPHAM.MADP NOT IN (
        SELECT DISTINCT CTPN.MADP
        FROM CTPN
        JOIN PHIEUNHAP ON CTPN.SOPN = PHIEUNHAP.SOPN
        WHERE PHIEUNHAP.MANCC = NHACUNGCAP.MANCC
        AND YEAR(PHIEUNHAP.NGNHAP) = 2017
    )
);
